<#
#   Intent: Creates a scheduled task that will run a script.
#   Author: Matthew Wurtz
#   Date: 28-Feb-25
#>

# Uses Base64 encoded string of the script for ease of use 
# Updated Base64 as of 3-Mar-25
$encodedCheck = "PAAjAA0ACgAjACAAIAAgAEkAbgB0AGUAbgB0ADoAIABDAHIAZQBhAHQAZQBzACAAYQAgAHMAYwBoAGUAZAB1AGwAZQBkACAAdABhAHMAawAgAHQAaABhAHQAIAB3AGkAbABsACAAcgB1AG4AIABhACAAcwBjAHIAaQBwAHQALgANAAoAIwAgACAAIABBAHUAdABoAG8AcgA6ACAATQBhAHQAdABoAGUAdwAgAFcAdQByAHQAegANAAoAIwAgACAAIABEAGEAdABlADoAIAAyADgALQBGAGUAYgAtADIANQANAAoAIwA+AA0ACgANAAoAIwAgAFUAcwBlAHMAIABCAGEAcwBlADYANAAgAGUAbgBjAG8AZABlAGQAIABzAHQAcgBpAG4AZwAgAG8AZgAgAHQAaABlACAAcwBjAHIAaQBwAHQAIABmAG8AcgAgAGUAYQBzAGUAIABvAGYAIAB1AHMAZQAgAA0ACgAjACAAVQBwAGQAYQB0AGUAZAAgAEIAYQBzAGUANgA0ACAAYQBzACAAbwBmACAAMwAtAE0AYQByAC0AMgA1AA0ACgAkAGUAbgBjAG8AZABlAGQAQwBoAGUAYwBrACAAPQAgACIAIgANAAoADQAKACMAPQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0ADQAKACMAIABHAGwAbwBiAGEAbAAgAFYAYQByAGEAaQBiAGwAZQBzACAAZgBvAHIAIABiAG8AdABoACAAUwBjAGgAZQBkAHUAbABlAGQAIABUAGEAcwBrAHMADQAKACMAPQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0ADQAKACQAdAByAGkAZwBnAGUAcgAgAD0AIABOAGUAdwAtAFMAYwBoAGUAZAB1AGwAZQBkAFQAYQBzAGsAVAByAGkAZwBnAGUAcgAgAC0AVwBlAGUAawBsAHkAIAAtAEQAYQB5AHMATwBmAFcAZQBlAGsAIABGAHIAaQBkAGEAeQAgAC0AQQB0ACAANABhAG0ADQAKACQAcwBlAHQAdABpAG4AZwBzACAAPQAgAE4AZQB3AC0AUwBjAGgAZQBkAHUAbABlAGQAVABhAHMAawBTAGUAdAB0AGkAbgBnAHMAUwBlAHQAIAAtAFcAYQBrAGUAVABvAFIAdQBuAA0ACgAkAHAAcgBpAG4AYwBpAHAAYQBsACAAPQAgAE4AZQB3AC0AUwBjAGgAZQBkAHUAbABlAGQAVABhAHMAawBQAHIAaQBuAGMAaQBwAGEAbAAgAC0AVQBzAGUAcgBJAGQAIAAiAE4AVAAgAEEAVQBUAEgATwBSAEkAVABZAFwAUwBZAFMAVABFAE0AIgAgAC0ATABvAGcAbwBuAFQAeQBwAGUAIABTAGUAcgB2AGkAYwBlAEEAYwBjAG8AdQBuAHQADQAKAA0ACgAjAD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQANAAoAIwAgAEMAcgBlAGEAdABlACAAQwBoAGUAYwBrAC0AUwBDAEMATQBIAGUAYQBsAHQAaAAgAFQAYQBzAGsADQAKACMAPQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AA0ACgAkAGEAYwB0AGkAbwBuACAAPQAgAE4AZQB3AC0AUwBjAGgAZQBkAHUAbABlAGQAVABhAHMAawBBAGMAdABpAG8AbgAgAC0ARQB4AGUAYwB1AHQAZQAgACIAcABvAHcAZQByAHMAaABlAGwAbAAuAGUAeABlACIADQAKACAAIAAgACAALQBBAHIAZwB1AG0AZQBuAHQAIAAiAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAEUAeABlAGMAdQB0AGkAbwBuAFAAbwBsAGkAYwB5ACAAQgB5AHAAYQBzAHMAIAAtAEUAbgBjAG8AZABlAGQAQwBvAG0AbQBhAG4AZAAgACQAZQBuAGMAbwBkAGUAZABDAGgAZQBjAGsAIgANAAoADQAKACQAZABlAHMAYwAgAD0AIAAiAFMAYwBoAGUAZAB1AGwAZQBkACAAdABhAHMAawAgAHQAbwAgAGMAcgBlAGEAdABlACAAcwBoAG8AcgB0AGMAdQB0AHMAIAB0AG8AIABzAHUAcgB2AGUAaQBsAGwAYQBuAGMAZQAgAG0AYQBjAGgAaQBuAGUAcwAuACIADQAKAA0ACgANAAoAUgBlAGcAaQBzAHQAZQByAC0AUwBjAGgAZQBkAHUAbABlAGQAVABhAHMAawAgAC0AVABhAHMAawBOAGEAbQBlACAAIgBDAHIAZQBhAHQAZQAtAFMAdQByAHYAUwBoAG8AcgB0AGMAdQB0AHMAIgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC0AQQBjAHQAaQBvAG4AIAAkAGEAYwB0AGkAbwBuAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAALQBUAHIAaQBnAGcAZQByACAAJAB0AHIAaQBnAGcAZQByAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAALQBzAGUAdAB0AGkAbgBnAHMAIAAkAHMAZQB0AHQAaQBuAGcAcwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC0AUAByAGkAbgBjAGkAcABhAGwAIAAkAHAAcgBpAG4AYwBpAHAAYQBsAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAALQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AIAAkAGQAZQBzAGMADQAKAA0ACgBpAGYAKABHAGUAdAAtAFMAYwBoAGUAZAB1AGwAZQBkAFQAYQBzAGsAIAAtAFQAYQBzAGsATgBhAG0AZQAgAEMAcgBlAGEAdABlAC0AUwB1AHIAdgBTAGgAbwByAHQAYwB1AHQAcwApAHsADQAKACAAIAAgACAAJAByAGUAcwB1AGwAdAAgAD0AIAAiAEMAcgBlAGEAdABlAGQAIABDAHIAZQBhAHQAZQAtAFMAdQByAHYAUwBoAG8AcgB0AGMAdQB0AHMAIAB0AGEAcwBrACIADQAKAH0AIABlAGwAcwBlAHsADQAKACAAIAAgACAAJAByAGUAcwB1AGwAdAAgAD0AIAAiAEYAYQBpAGwAZQBkACAAdABvACAAYwByAGUAYQB0AGUAIABDAHIAZQBhAHQAZQAtAFMAdQByAHYAUwBoAG8AcgB0AGMAdQB0AHMAIAB0AGEAcwBrACIADQAKAH0ADQAKAHIAZQB0AHUAcgBuACAAJAByAGUAcwB1AGwAdAA="

#==========================================
# Global Varaibles for both Scheduled Tasks
#==========================================
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Friday -At 4am
$settings = New-ScheduledTaskSettingsSet -WakeToRun
$principal = New-ScheduledTaskPrincipal -UserId "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount

#=============================
# Create Check-SCCMHealth Task
#=============================
$action = New-ScheduledTaskAction -Execute "powershell.exe"
    -Argument "-NoProfile -ExecutionPolicy Bypass -EncodedCommand $encodedCheck"

$desc = "Scheduled task to create shortcuts to surveillance machines."


Register-ScheduledTask -TaskName "Create-SurvShortcuts"
                       -Action $action
                       -Trigger $trigger
                       -settings $settings
                       -Principal $principal
                       -Description $desc

if(Get-ScheduledTask -TaskName Create-SurvShortcuts){
    $result = "Created Create-SurvShortcuts task"
} else{
    $result = "Failed to create Create-SurvShortcuts task"
}
return $result